unit TestUStore;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, UStore, URegister, UProductCatalog;

type
  // Test methods for class TSore

  TestTSore = class(TTestCase)
  strict private
    FSore: TSore;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  end;

implementation

procedure TestTSore.SetUp;
begin
  FSore := TSore.Create;
end;

procedure TestTSore.TearDown;
begin
  FSore.Free;
  FSore := nil;
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTSore.Suite);
end.

